### ISSUE TITLE
Point the updater to the 'firefox-legacy' branch

### ISSUE THREAD

**Issue by JustOff** [JustOff/ublock0-updater#10]
Since @gorhill [has moved](https://github.com/gorhill/uBlock/issues/3666#issuecomment-384944826) XUL-compatible version of `uBlock Origin` to the [firefox-legacy](https://github.com/gorhill/uBlock/tree/firefox-legacy) branch, `uBlock Origin Updater` needs to be updated [accordingly](https://github.com/gorhill/uBlock/commit/94de2222144626eccd3e4d939f1c46282836ed20#commitcomment-28770449).

**Comment by gorhill** [comment]
Also, the new package name is `uBlock0.firefox-legacy.xpi` -- this is to avoid confusion with the webext version which is now just named `uBlock0.firefox.xpi` (or `uBlock0.firefox.signed.xpi` for dev builds). New releases for `uBlock0.firefox-legacy.xpi` will happen only when something is fixed/changed in it.

**Comment by JustOff** [comment]
I accidentally guessed the name, but the algorithm for choosing the latest version still needs to be updated, which requires at least one release in the [firefox-legacy](https://github.com/gorhill/uBlock/tree/firefox-legacy) branch.

**Comment by gorhill** [comment]
I create a new [firefox-legacy-1.16.4](https://github.com/gorhill/uBlock/releases) release so you can move forward with the changes.

**Comment by JustOff** [comment]
Unfortunately it turned out that GitHub does not provide an API to get the latest release based on the specific branch, so that the uB0 Updater continue to work it is necessary to receive this info in some other way.

@gorhill, can I rely on the value from https://raw.githubusercontent.com/gorhill/uBlock/firefox-legacy/dist/version, so the latest legacy release will be always available at `https://github.com/gorhill/uBlock/releases/download/firefox-legacy-{$version}/uBlock0.firefox-legacy.xpi`?

**Comment by Vangelis66** [comment]
@JustOff 

... Using **Mozilla Firefox 53.0.3 32-bit portable** on a Windows x86 OS; browser has been patched to accept unsigned extensions (see [here](https://github.com/JustOff/ublock0-updater/issues/4#issuecomment-338329502)) ...
User-Agent: `Mozilla/5.0 (Windows NT 6.0; rv:53.0) Gecko/20100101 Firefox/53.0`

A week ago, latest **ublock0-updater-1.5.0.xpi** had been installed manually from the GitHub repo (not the APO site), followed by a manual install of **uBlock0.firefox-legacy.xpi** (then at version 1.6.4) from https://github.com/gorhill/uBlock/releases/ ; browser was restarted, uBlock0 filters updated manually. 

Today, in the add-ons manager, I manually checked (gear button) for extension updates: 

![aom1](https://user-images.githubusercontent.com/9669492/40519800-46ac086e-5fca-11e8-89e9-20cd13139240.jpg)

I was informed there's an update available to (legacy) uBlock0 1.16.4 !
When I switced to the `Available Updates` tab: 

![aom2](https://user-images.githubusercontent.com/9669492/40519868-c5f52632-5fca-11e8-8883-3116ec7732a8.jpg)

... I was prompted to update to **uBlock0 1.16.6**! 
Not knowing any better, and because I trust `ublock0-updater`, I thought a new legacy version had been issued and so went ahead with the update, only to end-up with **the Webextensions (stable) version of ublock0 v1.16.6** (which is also installable in Fx versions 52-56) 👎 

Any thoughts? 

I think I am revisiting [this](https://github.com/JustOff/ublock0-updater/issues/4#issuecomment-338344356) and [that](https://github.com/JustOff/ublock0-updater/issues/9#issuecomment-362951960) ... 😢 

As always, highly appreciative of your efforts 😄 
Kind regards

**Comment by JustOff** [comment]
@gorhill, it seems you tagged [1.16.4.7](https://github.com/gorhill/uBlock/releases/tag/1.16.4.7) release on the `master` branch, instead of the `firefox-legacy`, so uB0 Updater does not see it. Could you please fix this?

**Comment by gorhill** [comment]
I deleted/re-created the tagged release, but then I realized I am not sure what you mean. Are you saying 1.16.4.7 was the webext version of uBO?

**Comment by JustOff** [comment]
> I deleted/re-created the tagged release, but then I realized I am not sure what you mean. 

Unfortunately [1.16.4.7](https://github.com/gorhill/uBlock/releases/tag/1.16.4.7) still doesn't have `firefox-legacy` in the tag name, like [firefox-legacy-1.16.4.6](https://github.com/gorhill/uBlock/releases/tag/firefox-legacy-1.16.4.6) and all previous legacy releases had.

> Are you saying 1.16.4.7 was the webext version of uBO?

The package itself is ok, it's just about tags.

**Comment by gorhill** [comment]
Ok, I realize I didn't use the proper tag, I need to use `firefix-legacy-1.16.4.7`.

**Comment by JustOff** [comment]
Everything is ok now, thanks for your efforts!
