### ISSUE TITLE
uBlock Origin Updater has become obsolete

### ISSUE THREAD

**Issue by JustOff** [JustOff/ublock0-updater#112]
I'm pleased to announce that starting from version [1.16.4.17](https://github.com/gorhill/uBlock-for-firefox-legacy/releases/tag/firefox-legacy-1.16.4.17), uBlock Origin for Firefox legacy-based browsers can auto-update itself without any additional tricks. This also means that uBlock Origin Updater is becoming obsolete, and I'm going to make it so that it uninstalls itself on the next update.

**Comment by Symbian9** [comment]
Does it mean that with next Pale Moon update users, that already has installed uBO should not do nothing with hands and this transition would be automatic?

**Comment by JustOff** [comment]
> users, that already has installed uBO should not do nothing with hands

Exactly.

**Comment by rubyFeedback** [comment]
That's really convenient - I am using palemoon, and getting things installed was a bit cumbersome (also because I SUCK at searching + finding anything these days).

I could not surf the www without hero blockers (e. g. general content blockers) anymore, since I get way too much unnecessary information (aka spam). Google recently changed its search interface - it now takes me longer than before, even after daily use, to adjust to it. Anyway, getting off-topic, great news indeed. All power to the lazy ones - the lazy folks are the one driving forward a lot of the evolution of mankind! Why walk when you can fly. \o/

**Comment by happyniko** [comment]
Here is a link to my website. There are several add-ons. They all work with palemoon 28.8.2.1
[](https://www.trapp.co.at/Webbrowser/Pale-Moon/Pale-Moon-Add-ons/)

**Comment by JustOff** [comment]
@happyniko 
Please don't use this page to advertise any third-party resources.
