### ISSUE TITLE
Unable to Install (unsigned)

### ISSUE THREAD

**Issue by Joel889** [JustOff/ublock0-updater#4]
FF 48, xpinstall.signatures.required set to false. It will download the add-on, but then say that the add-on is unverified and can't be installed.

**Comment by JustOff** [comment]
[FF48 does not allow unsigned extensions to be installed, with no override](https://wiki.mozilla.org/Add-ons/Extension_Signing).

**Comment by Joel889** [comment]
Would there be a way to sign your addon?

**Comment by Vangelis66** [comment]
@Joel889 

If you're on Firefox **48.0** Release channel (BTW, **48.0.2** was the last update for major version 48) and you wish to install unsigned extensions (such as uBlock Origin and UBO&UM Updater) from Github repos, then head over to 
https://www.ghacks.net/2016/08/14/override-firefox-add-on-signing-requirement/ or 
http://www.largrizzly.net/firefox.html#pre55 
and do as instructed... I am attaching proof of the method working in the Greek locale of Firefox **52.0.2** Release channel (the last release channel version that would install on my OS, WinVistaSP2 32bit...): 

![proof](https://user-images.githubusercontent.com/9669492/31842167-6db26a04-b5f5-11e7-9421-938a7b8307da.jpg)
So, _there really is an override_ (a hack rather), but Mozilla would not want you to know about it... They're indeed aware about this hack, there's talk behind the curtains to disable it in Firefox Quantum (57.0+)  (currently unable to find the relevant bugzilla entry that I read just several days ago !) ...

**Comment by Vangelis66** [comment]
... Found it! You can read the discussion over at Bugzilla bug [#1292444](https://bugzilla.mozilla.org/show_bug.cgi?id=1292444)

**Comment by Joel889** [comment]
@Vangelis66 
Thank you so much! This worked like a charm!

**Comment by Vangelis66** [comment]
@JustOff

Hello :smile: . This is probably a separate issue on its own, but here you go: 

Firefox versions from 52.x to 56.x are eligible both for the WebExt version of uBO from [AMO](https://addons.mozilla.org/en-US/firefox/addon/ublock-origin/versions/beta) (_Firefox 52.0 and later_) and the XUL (legacy) version from [GitHub](https://github.com/gorhill/uBlock/blob/95f2fb6b11fa0815943414e8574862a5b7030db8/platform/firefox/install.rdf#L24). 

In Firefox **52.0.2** (see https://github.com/JustOff/ublock0-updater/issues/4#issuecomment-338329502) and **52.4.1** ESR installed on my Vista OS, I prefer to have the legacy version of uBlock Origin installed (rather than the WebExt flavour), hence the use of your extension... 

In both 52.0.2/52.4.1 I have disabled automatic extension updates and instead use the "check for updates + manual install" route; on several occasions when I'm offered an update (**beta** versions is checked in your extension options), I actually end up installing the webextension from AMO, instead of the legacy version (with the same version number) from GitHub :-1: 

What I think happens is the innate Firefox update mechanism kicks in first and offers me the (unwanted) update from AMO before your extension establishes there's an update from GitHub, too... However, this phenomenon is quite random, not always reproducible, so I suspect quite difficult to troubleshoot... 

As a rule of thumb, the majority of the times your extension behaves OK and I manually install the XUL uBO version, however once in a while (no discernible pattern in this behaviour) I get manually installed the WE one; so I must always check the type installed after an update and in the event I find the WE, uninstall it and then manually replace it with the XUL one... 

Do you think this issue could be investigated somehow, possibly remedied? 

BTW, as you might expect, I'm not facing this issue at all with Pale Moon 27.6.0a1 x86 (main browser now), 
because it will never be offered the WE from AMO... 

Thanks in advance :+1:

**Comment by JustOff** [comment]
> Do you think this issue could be investigated somehow, possibly remedied?

Sorry, but at the moment I've no idea how this can happen.

PS: Please always open a separate issue for unrelated topics.
